services:
  nginx:
    image: nginx:latest
    container_name: ml_nginx
    ports:
      - "8086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mlservice_blue
      - mlservice_green