services:
  mlservice_blue:
    build: .
    container_name: mlservice_blue
    environment:
      - MODEL_VERSION=v1.0.0
    ports:
      - "8082:8080"
    networks:
      - ml_network

  mlservice_green:
    build: .
    container_name: mlservice_green
    environment:
      - MODEL_VERSION=v1.1.0
    ports:
      - "8081:8080"
    networks:
      - ml_network

  nginx:
    image: nginx:latest
    container_name: ml_nginx
    ports:
      - "8086:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mlservice_blue
      - mlservice_green
    networks:
      - ml_network

networks:
  ml_network:
    driver: bridge